//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use serde::Serialize;
use sqlx::prelude::FromRow;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, FromRow, Hash)]
pub struct Song {
    pub id: Uuid,
    pub title: String,
    pub path: String,
    pub genre: String,
    pub suffix: String,
    pub content_type: String,
    pub track: i32,
    pub duration: i32,
    pub album_id: Uuid,
    pub disc_number: i32,
}

#[derive(FromRow, PartialEq, Eq, Hash, Clone, Debug, Serialize)]
pub struct SongSqlxModel {
    pub title: String,
    pub duration: i32,
    pub track: i32,
    pub album_id: Uuid,
    pub path: String,
    pub genre: String,
    pub suffix: String,
    pub content_type: String,
    pub disc_number: i32,
    pub id: Uuid,
    pub album_name: String,
    pub artist_name: String,
    pub year: i32,
    pub artist_id: Uuid,
}
