//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct User {
    pub id: Uuid,
    pub username: String,
    pub password: String,
}
